title: Title of your CV site
profile_img: /assets/img/picture.jpg
icon_img: /assets/img/icon.webp

name: "Hanieh Hatami"
job: "〈Your Job Here〉"

phone_number: +98-937-275-4514
address: Tehran, Iran
email: Haniehatami7@gmail.com
email: hanie.hatami@physics.sharif.edu
linkedin_username: @haniehtm
github_username: @haniehtm

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /resume
baseurl:

exclude:
  - _posts/
  - resources/
  - vendor/

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag